// Generated by CoffeeScript 1.10.0
var editor, exo1, exo2, exo3, exo4, workspace;

workspace = void 0;

editor = ace.edit("editor");

editor.getSession().setUseSoftTabs(false);

editor.getSession().setMode('ace/mode/python');

exo1 = {
  titre: "Boucle While",
  enonce: "Jean a mis en banque en 2012 un capital de 600 euros. Chaque année, il rajoute 76 euros sur ce compte. En quelle année dépassera-t-il les 1000€ ?"
};

exo2 = {
  titre: "Boucle While (avec appel de fonction)",
  enonce: "Jean a mis en banque en 2012 un capital de 600 euros. Chaque année, il rajoute 76 euros sur ce compte. En quelle année dépassera-t-il les 1000€ ?"
};

exo3 = {
  titre: "Boucle For",
  enonce: "Jeanne a mis en banque en début d’année un capital de 1500 euros. Chaque année, son capital est multiplié par 1,02. Dans 6 ans, de quelle somme disposera-t-il ?"
};

exo4 = {
  titre: "Boucle For (avec appel de fonction)",
  enonce: "Jeanne a mis en banque en début d’année un capital de 1500 euros. Chaque année, son capital est multiplié par 1,02. Dans 6 ans, de quelle somme disposera-t-il ?"
};

$(function() {
  var divsBlockly, divsPython, loadSample;
  $.ajax({
    type: "GET",
    url: "xml/exo3-toolbox.xml",
    dataType: "xml",
    success: function(xml) {
      workspace = Blockly.inject('blocklyDiv', {
        media: "js/vendor/blockly/media/",
        zoom: {
          controls: true,
          wheel: true,
          startScale: 1.1,
          maxScale: 3,
          minScale: 0.5,
          scaleSpeed: 1.2
        },
        toolbox: $(xml).find("#toolbox")[0]
      });
      Blockly.Msg.VARIABLES_SET = 'mettre %2 dans %1';
      return Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = 'regrouper';
    }
  });
  divsPython = "#pythonMode,  #boutons_editor";
  divsBlockly = "#blocklyMode, #boutons_blockly, .blocklyToolboxDiv";
  $(".toggleMode").on("click", function() {
    var texte;
    $(divsPython).toggle();
    $(divsBlockly).toggle();
    if ($("#pythonMode").is(":visible")) {
      texte = getPythonText();
      editor.setValue(tabuler(texte), -1);
      return editor.focus();
    }
  });
  $("#runBlocks").on("click", function() {
    return runBlockly();
  });
  $("#saveBlocks").on("click", function() {
    return sauverFichier();
  });
  $("#openBlocks").on("click", function() {
    return ouvrirClick();
  });
  $("#fileToLoad").on("change", function() {
    return ouvrirFichier();
  });
  $("#executer").on("click", function() {
    return runPython(editor);
  });
  $("#sauverFichierEdit").on("click", function() {
    return sauverFichierEdit(editor);
  });
  $("#ouvrirClickEdit").on("click", function() {
    return ouvrirClickEdit();
  });
  $("#fileToLoadEdit").on("change", function() {
    return ouvrirFichierEdit();
  });
  loadSample = function(name, exo) {
    $(divsPython).hide();
    $(divsBlockly).show();
    $("#enonce h2").html(exo.titre);
    $("#enonce p").html(exo.enonce);
    $("#enonce").show();
    workspace.clear();
    return $.ajax({
      type: "GET",
      url: "xml/" + name + ".xml",
      dataType: "xml",
      success: function(xml) {
        return Blockly.Xml.domToWorkspace($(xml).find("#" + name)[0], workspace);
      }
    });
  };
  $("#d0").on("click", function() {
    return loadSample("seuil0", exo1);
  });
  $("#d1").on("click", function() {
    return loadSample("seuil1", exo2);
  });
  $("#d2").on("click", function() {
    return loadSample("seuil2", exo3);
  });
  $("#d3").on("click", function() {
    return loadSample("seuil3", exo4);
  });
  Println('> 1) Il y a quelques exemples Blockly à tester...');
  return Println('> 2) Pour passer de Blockly à Python, cliquez sur le bouton Editeur...');
});
