// Generated by CoffeeScript 1.11.1
var editor, exo1, exo2, exo3, exo4, workspace;

workspace = void 0;

editor = ace.edit("editor");

editor.getSession().setUseSoftTabs(false);

editor.getSession().setMode('ace/mode/python');

exo1 = {
  titre: "Pentagone",
  enonce: "Votre mission si vous l'acceptez, est de programmer la tortue pour qu'elle dessine un pentagone régulier convexe."
};

exo2 = {
  titre: "Pentagone étoilé",
  enonce: "Maintenant la tortue devra dessiner une étoile à 5 branches. I didn't shoot the sheriff !"
};

exo3 = {
  titre: "Pentagramme",
  enonce: "Et maintenant les deux: Une étoile à 5 branches dans un pentagone"
};

exo4 = {
  titre: "Solution",
  enonce: "Voici un exemple de programme de pentagramme"
};

$(function() {
  var divsBlockly, divsPython, loadSample;
  $.ajax({
    type: "GET",
    url: "xml/exo4-toolbox.xml",
    dataType: "xml",
    success: function(xml) {
      workspace = Blockly.inject('blocklyDiv', {
        media: "js/vendor/blockly/media/",
        zoom: {
          controls: true,
          wheel: true,
          startScale: 1.1,
          maxScale: 3,
          minScale: 0.5,
          scaleSpeed: 1.2
        },
        toolbox: $(xml).find("#toolbox")[0]
      });
      Blockly.Msg.VARIABLES_SET = 'mettre %2 dans %1';
      return Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = 'regrouper';
    }
  });
  divsPython = "#pythonMode,  #boutons_editor";
  divsBlockly = "#blocklyMode, #boutons_blockly, .blocklyToolboxDiv";
  $(".toggleMode").on("click", function() {
    var texte;
    $(divsPython).toggle();
    $(divsBlockly).toggle();
    if ($("#pythonMode").is(":visible")) {
      texte = getPythonText();
      editor.setValue(tabuler(texte), -1);
      return editor.focus();
    }
  });
  $("#runBlocks").on("click", function() {
    return runBlockly();
  });
  $("#saveBlocks").on("click", function() {
    return sauverFichier();
  });
  $("#openBlocks").on("click", function() {
    return ouvrirClick();
  });
  $("#fileToLoad").on("change", function() {
    return ouvrirFichier();
  });
  $("#executer").on("click", function() {
    return runPython(editor);
  });
  $("#sauverFichierEdit").on("click", function() {
    return sauverFichierEdit(editor);
  });
  $("#ouvrirClickEdit").on("click", function() {
    return ouvrirClickEdit();
  });
  $("#fileToLoadEdit").on("change", function() {
    return ouvrirFichierEdit();
  });
  $("#py2algo").on("click", function() {
    return afficherPseudocode();
  });
  loadSample = function(name, exo) {
    $(divsPython).hide();
    $(divsBlockly).show();
    $("#enonce h2").html(exo.titre);
    $("#enonce p").html(exo.enonce);
    $("#enonce").show();
    workspace.clear();
    return $.ajax({
      type: "GET",
      url: "xml/" + name + ".xml",
      dataType: "xml",
      success: function(xml) {
        return Blockly.Xml.domToWorkspace($(xml).find("#" + name)[0], workspace);
      }
    });
  };
  $("#t0").on("click", function() {
    return loadSample("turtle0", exo1);
  });
  $("#t1").on("click", function() {
    return loadSample("pentagone1", exo2);
  });
  $("#t2").on("click", function() {
    return loadSample("pentagone2", exo3);
  });
  return $("#t3").on("click", function() {
    return loadSample("pentagramme", exo4);
  });
});
